apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-server-conf
  namespace : wso2is
data:
  deployment.toml: |-
    [server]
    hostname = "$env{HOST_NAME}"
    node_ip = "$env{NODE_IP}"
    # base_path = "https://$ref{server.hostname}:${carbon.management.port}"

    [super_admin]
    username = "admin"
    password = "admin"
    create_admin_account = true

    [user_store]
    type = "database_unique_id"

    [database.identity_db]
    type = "mysql"
    url = "jdbc:mysql://wso2is-rdbms-service-mysql:3306/WSO2IS_IDENTITY_DB?autoReconnect=true&amp;useSSL=false"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"
    [database.identity_db.pool_options]
    validationQuery = "SELECT 1"


    [database.shared_db]
    type = "mysql"
    url = "jdbc:mysql://wso2is-rdbms-service-mysql:3306/WSO2IS_SHARED_DB?autoReconnect=true&amp;useSSL=false"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"
    [database.shared_db.pool_options]
    validationQuery = "SELECT 1"

    [keystore.primary]
    file_name = "wso2carbon.jks"
    password = "wso2carbon"